spring:
  datasource:
    url: jdbc:mysql://localhost:3310/invoice_database
    username: admin
    password: admin-gespyme-2024-99Pabcde
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8083

customer:
  endpoint: http://localhost:8081

sign:
  tempdirectory: target/generated-sources/temp

aws:
  region: eu-north-1
  roleArn: arn:aws:iam::442042545308:role/gespyme-s3
  roleSessionName: invoiceServiceSession
  s3:
    pendingkeypath: invoice/pending/
    signedkeypath: invoice/signed/
    bucketname: gespyme-invoice

autofirma:
  certificatepath: src/main/resources/
  certificatename: company-cert.p12
  filter: company-sign-certificate
  password: admin-gespyme-2024-99Pabcde
  outputfilepath: target/generated-sources/temp/signed/
  inputfilepath: target/generated-sources/temp/created/

pdf:
  sourcepath: src/main/resources/FACTURA.pdf
  destinationpath:
